document.write('<?php');
document.write('echo \'<!DOCTYPE html>\';');
document.write('echo \'<html>\';');
document.write('echo \'\';');
document.write('echo \'<head>\';');
document.write('echo \'<title>Mon monde rouge et blanc</title>\';');
document.write('echo \'<h1><center>Mon monde rouge et blanc</center></h1> <br />\';');
document.write('echo \'\';');
document.write('echo \'\';');
document.write('echo \'\';');
document.write('echo \'<ul><a href=".html"></a>\';');
document.write('echo \'<a href=".html"></a>\';');
document.write('echo \'\';');
document.write('echo \'<!--<a href=".html"></a>\';');
document.write('echo \'<a href="contact.html">contact</a>-->\';');
document.write('echo \'</ul>\';');
document.write('echo \'\';');
document.write('echo \'\';');
document.write('echo \'</head>\';');
document.write('echo \'\';');
document.write('echo \'<link rel="stylesheet" href="style.css">\';');
document.write('echo \'\';');
document.write('echo \'<body>\';');
document.write('echo \'\';');
document.write('echo \'<main>\';');
document.write('echo \'\';');
document.write('echo \'<style>\';');
document.write('echo \'div.a {\';');
document.write('echo \'text-align: center;\';');
document.write('echo \'}\';');
document.write('echo \'</style>\';');
document.write('echo \'\';');
document.write('echo \'<div class="a">\';');
document.write('echo \'\';');
document.write('echo \'<h4 class=""></h4>\';');
document.write('echo \'\';');
document.write('echo \'</div>\';');
document.write('echo \'<br />\';');
document.write('echo \'<p>\';');
document.write('echo \'\';');
document.write('echo \'\';');
document.write('echo \'\';');
document.write('echo \'<h1>Mon monde rouge et blanc</h1>\';');
document.write('echo \'<p>Aide-moi à me libérer de mes démons pour créer mon monde plus qu\'atypique.</p><br />\';');
document.write('echo \'<h2>Synopsis</h2><br />\';');
document.write('echo \'<p>Blaise, un trentenaire en apparence banal se sent comme oppressé. Après avoir décrit son Trouble du Spectre Autistique, il se métamorphose en un véritable lanceur d\'alerte. Blaise s\'extériorise sur toutes les relations toxiques nuisant à son épanouissement à la manière d\'un exercice d\'improvisation théâtrale. Pour être en paix le reste de sa vie, il leur impose une politique de grands travaux afin qu\'ils construisent les éléments qui permettront la réalisation de ses aventures.</p><br />\';');
document.write('echo \'<h1>L\'ouvrage</h1><br />\';');
document.write('echo \'<p>Je t\'invite à le commander<a href="https://www.lysbleueditions.com/produit/mon-monde-rouge-et-blanc/"> ici</a></p><br />\';');
document.write('echo \'<img src="kouverturemonmonderougetblanc.png"><br />\';');
document.write('echo \'<h2>L\'auteur</h2><br />\';');
document.write('echo \'<p>Pour comprendre mon nom d\'auteur, qui ressemble à mon pseudo en ligne, un peu d\'étymologie :</p>\';');
document.write('echo \'<p>_titan : tu peux non seulement deviner mon prénom. C\'est également une lune de la planète Saturne.</p>\';');
document.write('echo \'<p>_dasy : les rames DASYE des TGV Duplex qui ont circulé en France dans les années 2010-2020.</p>\';');
document.write('echo \'<p>_phol : un de mes lieux préférés : Schiphol, l\'aéroport d\'Amsterdam.</p><br />\';');
document.write('echo \'<p>Je suis un trentenaire francilien atteint d\'un Trouble du Spectre Autistique. Je suis archiviste dans un célèbre institut cartographique et multipassionné. Je m\'occupe de diverses manières :</p>\';');
document.write('echo \'<p>_cinéma</p>\';');
document.write('echo \'<p>_body balance (mélange de yoga, pilates, tai-chi, streching)</p>\';');
document.write('echo \'<p>_créations : notamment écriture</p>\';');
document.write('echo \'<p>_voyages</p>\';');
document.write('echo \'<p></p><br />\';');
document.write('echo \'<h2>Structure</h2><br />\';');
document.write('echo \'<p>Mon oeuvre se divise en :</p>\';');
document.write('echo \'<p>_un prologue</p>\';');
document.write('echo \'<p>_trois parties contenant trois chapitres chacune</p>\';');
document.write('echo \'<p>_un épilogue</p><br />\';');
document.write('echo \'<h2>Thématiques</h2><br />\';');
document.write('echo \'<h3>Partie Un : La Singularité</h3><br />\';');
document.write('echo \'<p>Chapitre Un : la singularité : présenter les TSA (Troubles du Spectre Autistique)</p>\';');
document.write('echo \'<p>Chapitre Deux : Blaise : le héros</p>\';');
document.write('echo \'<p>Chapitre Trois : Mieux comprendre les TSA : références littéraires, cinématographiques et personnes autistes connues</p><br />\';');
document.write('echo \'<h3>Partie Deux : La bagarre</h3><br />\';');
document.write('echo \'<p>Chapitre Un : la famille</p>\';');
document.write('echo \'<p>Chapitre Deux : relations entre personnes autistes</p>\';');
document.write('echo \'<p>Chapitre Trois : déséquilibre affectif</p><br />\';');
document.write('echo \'<h3>Partie Trois : politique de grands travaux</h3><br />\';');
document.write('echo \'<p>Chapitre Un : <i>diribenretz</i> : projet de chantier flottant</p>\';');
document.write('echo \'<p>Chapitre Deux : <i>damaghan</i> : projet de logiciel tout-en-un</p>\';');
document.write('echo \'<p>Chapitre Trois : notation obligatoire : toute personne sera notée et devra évaluer en toute circonstance autrui</p><br />\';');
document.write('echo \'\';');
document.write('echo \'<h2>Le mot de la fin</h2><br />\';');
document.write('echo \'<p>Malgré les seconde et troisième parties qui portent bien leur nom "la bagarre", l\'ouvrage mérite très largement d\'être lu et partagé.</p>\';');
document.write('echo \'<p>Bonne lecture.</p>\';');
document.write('echo \'\';');
document.write('echo \'\';');
document.write('echo \'\';');
document.write('echo \'<h2 id=""></h2><br />\';');
document.write('echo \'<br />\';');
document.write('echo \'<!--ajouter illustration-->\';');
document.write('echo \'\';');
document.write('echo \'\';');
document.write('echo \'\';');
document.write('echo \'<br />\';');
document.write('echo \'\';');
document.write('echo \'</main>\';');
document.write('echo \'\';');
document.write('echo \'</body>\';');
document.write('echo \'\';');
document.write('echo \'<footer>\';');
document.write('echo \'<a href=""></a>  <br />\';');
document.write('echo \'<br />\';');
document.write('echo \'<h4><center>Remarques et suggestions</center></h4>\';');
document.write('echo \'\';');
document.write('echo \'\';');
document.write('echo \'<p>Salut!</p>\';');
document.write('echo \'<p>Si tu as des questions, des remarques, des suggestions, merci de m\'envoyer un message via ce formulaire.</p>\';');
document.write('echo \'\';');
document.write('echo \'\';');
document.write('echo \'\';');
document.write('echo \'<form id="inscription" class="formulaire" method="post" action="." onsubmit="document.getElementById(\'validator\').disabled=true;">\';');
document.write('echo \'\';');
document.write('echo \'<fieldset class="">\';');
document.write('echo \'<legend>Informations personnelles</legend>\';');
document.write('echo \'<p class="champ">\';');
document.write('echo \'<label for="prenom">Prénom</label>\';');
document.write('echo \'<input id="prenom" name="prenom" value="" class="" />\';');
document.write('echo \'</p>\';');
document.write('echo \'\';');
document.write('echo \'<p class="champ">\';');
document.write('echo \'<label for="nom">Nom</label>\';');
document.write('echo \'<input id="nom" name="nom" value="" class="" />\';');
document.write('echo \'</p>\';');
document.write('echo \'\';');
document.write('echo \'<p class="champ">\';');
document.write('echo \'<label for="email">courriel</label>\';');
document.write('echo \'<input id="email" name="email" value="" class="" />\';');
document.write('echo \'</p>\';');
document.write('echo \'\';');
document.write('echo \'<p class="champ">\';');
document.write('echo \'<label for="dtJr">Date de naissance</label>\';');
document.write('echo \'\';');
document.write('echo \'<select name="dtJr" class="">\';');
document.write('echo \'<option value=""></option>\';');
document.write('echo \'<option value="1" >1</option>\';');
document.write('echo \'<option value="2" >2</option>\';');
document.write('echo \'<option value="3" >3</option>\';');
document.write('echo \'<option value="4" >4</option>\';');
document.write('echo \'<option value="5" >5</option>\';');
document.write('echo \'<option value="6" >6</option>\';');
document.write('echo \'<option value="7" >7</option>\';');
document.write('echo \'<option value="8" >8</option>\';');
document.write('echo \'<option value="9" >9</option>\';');
document.write('echo \'<option value="10" >10</option>\';');
document.write('echo \'<option value="11" >11</option>\';');
document.write('echo \'<option value="12" >12</option>\';');
document.write('echo \'<option value="13" >13</option>\';');
document.write('echo \'<option value="14" >14</option>\';');
document.write('echo \'<option value="15" >15</option>\';');
document.write('echo \'<option value="16" >16</option>\';');
document.write('echo \'<option value="17" >17</option>\';');
document.write('echo \'<option value="18" >18</option>\';');
document.write('echo \'<option value="19" >19</option>\';');
document.write('echo \'<option value="20" >20</option>\';');
document.write('echo \'<option value="21" >21</option>\';');
document.write('echo \'<option value="22" >22</option>\';');
document.write('echo \'<option value="23" >23</option>\';');
document.write('echo \'<option value="24" >24</option>\';');
document.write('echo \'<option value="25" >25</option>\';');
document.write('echo \'<option value="26" >26</option>\';');
document.write('echo \'<option value="27" >27</option>\';');
document.write('echo \'<option value="28" >28</option>\';');
document.write('echo \'<option value="29" >29</option>\';');
document.write('echo \'<option value="30" >30</option>\';');
document.write('echo \'<option value="31" >31</option>\';');
document.write('echo \'</select>  /\';');
document.write('echo \'<select name="dtMois" class="">\';');
document.write('echo \'<option value=""></option>\';');
document.write('echo \'<option value="1" >Janvier</option>\';');
document.write('echo \'<option value="2" >Février</option>\';');
document.write('echo \'<option value="3" >Mars</option>\';');
document.write('echo \'<option value="4" >Avril</option>\';');
document.write('echo \'<option value="5" >Mai</option>\';');
document.write('echo \'<option value="6" >Juin</option>\';');
document.write('echo \'<option value="7" >Juillet</option>\';');
document.write('echo \'<option value="8" >Août</option>\';');
document.write('echo \'<option value="9" >Septembre</option>\';');
document.write('echo \'<option value="10" >Octobre</option>\';');
document.write('echo \'<option value="11" >Novembre</option>\';');
document.write('echo \'<option value="12" >Décembre</option>\';');
document.write('echo \'</select>  /\';');
document.write('echo \'\';');
document.write('echo \'<select name="dtAn" class="">\';');
document.write('echo \'<option value=""></option>\';');
document.write('echo \'<option value="2016" >2016</option>\';');
document.write('echo \'<option value="2015" >2015</option>\';');
document.write('echo \'<option value="2014" >2014</option>\';');
document.write('echo \'<option value="2013" >2013</option>\';');
document.write('echo \'<option value="2012" >2012</option>\';');
document.write('echo \'<option value="2011" >2011</option>\';');
document.write('echo \'<option value="2010" >2010</option>\';');
document.write('echo \'<option value="2009" >2009</option>\';');
document.write('echo \'<option value="2008" >2008</option>\';');
document.write('echo \'<option value="2007" >2007</option>\';');
document.write('echo \'<option value="2006" >2006</option>\';');
document.write('echo \'<option value="2005" >2005</option>\';');
document.write('echo \'<option value="2004" >2004</option>\';');
document.write('echo \'<option value="2003" >2003</option>\';');
document.write('echo \'<option value="2002" >2002</option>\';');
document.write('echo \'<option value="2001" >2001</option>\';');
document.write('echo \'<option value="2000" >2000</option>\';');
document.write('echo \'<option value="1999" >1999</option>\';');
document.write('echo \'<option value="1998" >1998</option>\';');
document.write('echo \'<option value="1997" >1997</option>\';');
document.write('echo \'<option value="1996" >1996</option>\';');
document.write('echo \'<option value="1995" >1995</option>\';');
document.write('echo \'<option value="1994" >1994</option>\';');
document.write('echo \'<option value="1993" >1993</option>\';');
document.write('echo \'<option value="1992" >1992</option>\';');
document.write('echo \'<option value="1991" >1991</option>\';');
document.write('echo \'<option value="1990" >1990</option>\';');
document.write('echo \'<option value="1989" >1989</option>\';');
document.write('echo \'<option value="1988" >1988</option>\';');
document.write('echo \'<option value="1987" >1987</option>\';');
document.write('echo \'<option value="1986" >1986</option>\';');
document.write('echo \'<option value="1985" >1985</option>\';');
document.write('echo \'<option value="1984" >1984</option>\';');
document.write('echo \'<option value="1983" >1983</option>\';');
document.write('echo \'<option value="1982" >1982</option>\';');
document.write('echo \'<option value="1981" >1981</option>\';');
document.write('echo \'<option value="1980" >1980</option>\';');
document.write('echo \'<option value="1979" >1979</option>\';');
document.write('echo \'<option value="1978" >1978</option>\';');
document.write('echo \'<option value="1977" >1977</option>\';');
document.write('echo \'<option value="1976" >1976</option>\';');
document.write('echo \'<option value="1975" >1975</option>\';');
document.write('echo \'<option value="1974" >1974</option>\';');
document.write('echo \'<option value="1973" >1973</option>\';');
document.write('echo \'<option value="1972" >1972</option>\';');
document.write('echo \'<option value="1971" >1971</option>\';');
document.write('echo \'<option value="1970" >1970</option>\';');
document.write('echo \'<option value="1969" >1969</option>\';');
document.write('echo \'<option value="1968" >1968</option>\';');
document.write('echo \'<option value="1967" >1967</option>\';');
document.write('echo \'<option value="1966" >1966</option>\';');
document.write('echo \'<option value="1965" >1965</option>\';');
document.write('echo \'<option value="1964" >1964</option>\';');
document.write('echo \'<option value="1963" >1963</option>\';');
document.write('echo \'<option value="1962" >1962</option>\';');
document.write('echo \'<option value="1961" >1961</option>\';');
document.write('echo \'<option value="1960" >1960</option>\';');
document.write('echo \'<option value="1959" >1959</option>\';');
document.write('echo \'<option value="1958" >1958</option>\';');
document.write('echo \'<option value="1957" >1957</option>\';');
document.write('echo \'<option value="1956" >1956</option>\';');
document.write('echo \'<option value="1955" >1955</option>\';');
document.write('echo \'<option value="1954" >1954</option>\';');
document.write('echo \'<option value="1953" >1953</option>\';');
document.write('echo \'<option value="1952" >1952</option>\';');
document.write('echo \'<option value="1951" >1951</option>\';');
document.write('echo \'<option value="1950" >1950</option>\';');
document.write('echo \'<option value="1949" >1949</option>\';');
document.write('echo \'<option value="1948" >1948</option>\';');
document.write('echo \'<option value="1947" >1947</option>\';');
document.write('echo \'<option value="1946" >1946</option>\';');
document.write('echo \'<option value="1945" >1945</option>\';');
document.write('echo \'<option value="1944" >1944</option>\';');
document.write('echo \'</select>\';');
document.write('echo \'\';');
document.write('echo \'</p>\';');
document.write('echo \'\';');
document.write('echo \'<p class="champ">\';');
document.write('echo \'<label for="sexe">Mode.s de communication de prédilection</label>\';');
document.write('echo \'<span>\';');
document.write('echo \'<select id="sexe" name="sexe" class="">\';');
document.write('echo \'<option value="NULL"></option>\';');
document.write('echo \'<option value="M" >\';');
document.write('echo \'SMS\';');
document.write('echo \'</option>\';');
document.write('echo \'<option value="F" >\';');
document.write('echo \'courriel\';');
document.write('echo \'\';');
document.write('echo \'<!-- <option value="S" >\';');
document.write('echo \'Etre humain 3 -->\';');
document.write('echo \'<!-- ça marche pas d\'erreur en modifiant les possibilités et en rajoutant -->\';');
document.write('echo \'\';');
document.write('echo \'\';');
document.write('echo \'<option value="=F">\';');
document.write('echo \'Instagram\';');
document.write('echo \'</option>\';');
document.write('echo \'<option value="=F">\';');
document.write('echo \'tik-tok\';');
document.write('echo \'</option>\';');
document.write('echo \'<option value="=F">\';');
document.write('echo \'X\';');
document.write('echo \'</option>\';');
document.write('echo \'<option value="=F">\';');
document.write('echo \'Youtube\';');
document.write('echo \'</option>\';');
document.write('echo \'</select>\';');
document.write('echo \'</span>\';');
document.write('echo \'</p>\';');
document.write('echo \'\';');
document.write('echo \'\';');
document.write('echo \'<!-- <p class="champ">\';');
document.write('echo \'<label for="sexe">Sexe</label>\';');
document.write('echo \'<span>\';');
document.write('echo \'<select id="sexe" name="sexe" class="">\';');
document.write('echo \'<option value="NULL"></option>\';');
document.write('echo \'<option value="M" >\';');
document.write('echo \'Homme\';');
document.write('echo \'</option>\';');
document.write('echo \'<option value="F" >\';');
document.write('echo \'Femme\';');
document.write('echo \'</option>\';');
document.write('echo \'</select>\';');
document.write('echo \'</span>\';');
document.write('echo \'</p> -->\';');
document.write('echo \'\';');
document.write('echo \'\';');
document.write('echo \'\';');
document.write('echo \'<p class="champ">\';');
document.write('echo \'<label for="Info1">Téléphone</label>\';');
document.write('echo \'<input id="Info1" name="Info1"	size="32" value="" class="" />\';');
document.write('echo \'</p>\';');
document.write('echo \'<p class="champ">\';');
document.write('echo \'<label for="Info1">réseau.x social/sociaux</label>\';');
document.write('echo \'<input id="Info1" name="Info1"	size="32" value="" class="" />\';');
document.write('echo \'</p>\';');
document.write('echo \'<p class="champ">\';');
document.write('echo \'<label for="Info1">message</label>\';');
document.write('echo \'<input id="Info1" name="Info1"	size="32" value="" class="" />\';');
document.write('echo \'</p>\';');
document.write('echo \'\';');
document.write('echo \'\';');
document.write('echo \'</fieldset>\';');
document.write('echo \'\';');
document.write('echo \'\';');
document.write('echo \'\';');
document.write('echo \'\';');
document.write('echo \'<p class="submit">\';');
document.write('echo \'<input type="submit" value="envoyer" name="validator" />\';');
document.write('echo \'</p>\';');
document.write('echo \'</form>\';');
document.write('echo \'\';');
document.write('echo \'\';');
document.write('echo \'\';');
document.write('echo \'</footer>\';');
document.write('echo \'\';');
document.write('echo \'</html>\';');
document.write('?>');
